spring:
  security:
    user:
      password: password
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Access-Control-Allow-Origin, *
        - StripPrefix=1
      routes:
        - id: couchdb
          uri: http://couchdb:5984
          predicates:
            - Path=/couchdb/**
          filters:
            - AddCouchDBAuthHeaders=92de07df7e7a3fe14808cef90a7cc0d91
            - SetUserCookie
        - id: app
          uri: http://data-app
          predicates:
            - Path=/app/**
          filters:
            - AddCouchDBAuthHeaders=92de07df7e7a3fe14808cef90a7cc0d91
            - SetUserCookie

logging:
  level:
    root: ERROR
    com.example.apigateway: DEBUG